name: Youtube Playlist 2 Telegram

on:
  workflow_dispatch:
    inputs:
      link:
        description: 'link'
        required: true
        default: '0'
      quality:
        description: 'quality '
        required: false
        default: '22'


jobs:
  Update:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install yt-dlp
        run: sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp; sudo chmod a+rx /usr/local/bin/yt-dlp;
      - name: Install aria2 ffmpeg tree 
        run: sudo apt update; sudo apt install -y aria2 ffmpeg; cp ytdlp/yt-plist.conf yt-dlp.conf;
      - name: Download
        run: yt-dlp -f '${{ github.event.inputs.quality }}' '${{ github.event.inputs.link }}'
      - name: View
        run: tree -a .
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run
        env:
          apiHash: ${{ secrets.apiHash }}
          apiId: ${{ secrets.apiId }}
          apiUrl: ${{ secrets.apiUrl }}
          mdpass: ${{ secrets.mdpass }}
          mdurl: ${{ secrets.mdurl }}
          mduser: ${{ secrets.mduser }}
          tgPass: ${{ secrets.tgPass }}
          tgPhone: ${{ secrets.tgPhone }}
        run: |
          python Main.py
      
